//! Authoritative TypeScript/JavaScript environment classification.
//!
//! Language built-ins are intrinsic names supplied by ECMAScript or
//! TypeScript and do not become graph nodes. Platform globals are supplied by
//! a host environment and remain visible as `External(AmbientGlobal)` nodes.

pub(crate) fn is_language_value_builtin(name: &str) -> bool {
    matches!(
        name,
        "true"
            | "false"
            | "null"
            | "this"
            | "super"
            | "globalThis"
            | "arguments"
            | "undefined"
            | "NaN"
            | "Infinity"
            | "Error"
            | "EvalError"
            | "RangeError"
            | "ReferenceError"
            | "SyntaxError"
            | "TypeError"
            | "URIError"
            | "AggregateError"
            | "Array"
            | "ArrayBuffer"
            | "BigInt"
            | "BigInt64Array"
            | "BigUint64Array"
            | "Boolean"
            | "DataView"
            | "Date"
            | "Float32Array"
            | "Float64Array"
            | "Function"
            | "Int8Array"
            | "Int16Array"
            | "Int32Array"
            | "Map"
            | "Number"
            | "Object"
            | "Promise"
            | "RegExp"
            | "Set"
            | "String"
            | "Symbol"
            | "Uint8Array"
            | "Uint8ClampedArray"
            | "Uint16Array"
            | "Uint32Array"
            | "WeakMap"
            | "WeakSet"
            | "FinalizationRegistry"
            | "WeakRef"
            | "Proxy"
            | "Math"
            | "JSON"
            | "Reflect"
            | "Intl"
            | "parseInt"
            | "parseFloat"
            | "isNaN"
            | "isFinite"
            | "encodeURI"
            | "encodeURIComponent"
            | "decodeURI"
            | "decodeURIComponent"
            | "console"
            | "jest"
            | "vi"
            | "describe"
            | "xdescribe"
            | "fdescribe"
            | "it"
            | "xit"
            | "fit"
            | "test"
            | "xtest"
            | "expect"
            | "expectTypeOf"
            | "before"
            | "beforeAll"
            | "beforeEach"
            | "after"
            | "afterAll"
            | "afterEach"
            | "assert"
    )
}

pub(crate) fn is_language_type_builtin(name: &str) -> bool {
    matches!(
        name,
        "Array"
            | "ReadonlyArray"
            | "Promise"
            | "PromiseLike"
            | "Map"
            | "ReadonlyMap"
            | "Set"
            | "ReadonlySet"
            | "WeakMap"
            | "WeakSet"
            | "WeakRef"
            | "FinalizationRegistry"
            | "Date"
            | "RegExp"
            | "Object"
            | "Function"
            | "Error"
            | "EvalError"
            | "RangeError"
            | "ReferenceError"
            | "SyntaxError"
            | "TypeError"
            | "URIError"
            | "AggregateError"
            | "Number"
            | "String"
            | "Boolean"
            | "Symbol"
            | "BigInt"
            | "ArrayBuffer"
            | "SharedArrayBuffer"
            | "DataView"
            | "Int8Array"
            | "Uint8Array"
            | "Uint8ClampedArray"
            | "Int16Array"
            | "Uint16Array"
            | "Int32Array"
            | "Uint32Array"
            | "Float32Array"
            | "Float64Array"
            | "BigInt64Array"
            | "BigUint64Array"
            | "Proxy"
            | "Partial"
            | "Required"
            | "Readonly"
            | "Record"
            | "Pick"
            | "Omit"
            | "Exclude"
            | "Extract"
            | "NonNullable"
            | "Parameters"
            | "ConstructorParameters"
            | "ReturnType"
            | "InstanceType"
            | "ThisParameterType"
            | "OmitThisParameter"
            | "ThisType"
            | "Uppercase"
            | "Lowercase"
            | "Capitalize"
            | "Uncapitalize"
            | "Awaited"
            | "NoInfer"
            | "Iterable"
            | "Iterator"
            | "IteratorResult"
            | "IterableIterator"
            | "AsyncIterable"
            | "AsyncIterator"
            | "AsyncIterableIterator"
            | "Generator"
            | "AsyncGenerator"
            | "ArrayLike"
            | "IArguments"
            | "TemplateStringsArray"
            | "PropertyKey"
            | "PropertyDescriptor"
            | "TypedPropertyDescriptor"
    )
}

pub(crate) fn is_platform_value_global(name: &str) -> bool {
    matches!(
        name,
        "indexedDB"
            | "document"
            | "window"
            | "self"
            | "navigator"
            | "location"
            | "history"
            | "global"
            | "crypto"
            | "Bun"
            | "Deno"
            | "WebSocketPair"
            | "awslambda"
            | "localStorage"
            | "sessionStorage"
            | "fetch"
            | "process"
            | "Buffer"
            | "require"
            | "module"
            | "__dirname"
            | "__filename"
            | "setTimeout"
            | "setInterval"
            | "setImmediate"
            | "clearTimeout"
            | "clearInterval"
            | "cancelAnimationFrame"
            | "addEventListener"
            | "requestAnimationFrame"
            | "queueMicrotask"
            | "btoa"
            | "atob"
            | "caches"
            | "eval"
            | "performance"
            | "structuredClone"
    ) || is_platform_class_global(name)
}

pub(crate) fn is_platform_type_global(name: &str) -> bool {
    is_platform_class_global(name)
        || matches!(
            name,
            "Document"
                | "Element"
                | "History"
                | "JsonWebKey"
                | "Location"
                | "Navigator"
                | "RequestInit"
                | "Storage"
                | "StorageEvent"
                | "Window"
        )
}

fn is_platform_class_global(name: &str) -> bool {
    matches!(
        name,
        "AbortController"
            | "AbortSignal"
            | "Blob"
            | "CloseEvent"
            | "CompressionStream"
            | "CustomEvent"
            | "CryptoKey"
            | "DecompressionStream"
            | "DOMException"
            | "Event"
            | "EventTarget"
            | "File"
            | "FileList"
            | "FileReader"
            | "FormData"
            | "Headers"
            | "HTMLButtonElement"
            | "HTMLCanvasElement"
            | "HTMLDivElement"
            | "HTMLElement"
            | "HTMLFormElement"
            | "HTMLInputElement"
            | "HTMLSpanElement"
            | "Image"
            | "ImageData"
            | "IntersectionObserver"
            | "KeyboardEvent"
            | "MessageEvent"
            | "MouseEvent"
            | "Node"
            | "ReadableStream"
            | "ReadableStreamDefaultController"
            | "Request"
            | "Response"
            | "SVGElement"
            | "SubmitEvent"
            | "TextDecoder"
            | "TextDecoderStream"
            | "TextEncoder"
            | "TextEncoderStream"
            | "TransformStream"
            | "URL"
            | "URLSearchParams"
            | "WritableStream"
            | "WebSocket"
            | "EventSource"
    )
}
